import type { Metadata } from "next";
import Navigation from "./components/navigation";
import Footer from "./components/footer";

import "./globals.css";
import "./components/services.css"
import "./components/industries.css"
import "./components/About.css"

export const metadata: Metadata = {
  title: "OIAE Systems",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body ><Navigation />{children}<Footer /></body>
    </html>
  );
}
